export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

export const AUTH_USER = 'AUTH_USER';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const ADD_TO_CART_USER_REQUEST = 'ADD_TO_CART_USER_REQUEST';
export const ADD_TO_CART_USER_SUCCESS = 'ADD_TO_CART_USER_SUCCESS';
export const ADD_TO_CART_USER_FAILURE = 'ADD_TO_CART_USER_FAILURE';

export const GET_CART_ITEMS_USER_REQUEST = 'GET_CART_ITEMS_USER_REQUEST';
export const GET_CART_ITEMS_USER_SUCCESS = 'GET_CART_ITEMS_USER_SUCCESS';
export const GET_CART_ITEMS_USER_FAILURE = 'GET_CART_ITEMS_USER_FAILURE';

export const POST_DETAIL_LOADING_REQUEST = 'POST_DETAIL_LOADING_REQUEST';
export const POST_DETAIL_LOADING_SUCCESS = 'POST_DETAIL_LOADING_SUCCESS';
export const POST_DETAIL_LOADING_FAILURE = 'POST_DETAIL_LOADING_FAILURE';

export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAILURE = 'PROFILE_EDIT_FAILURE';

export const COMMENT_UPLOADING_REQUEST = 'COMMENT_UPLOADING_REQUEST';
export const COMMENT_UPLOADING_SUCCESS = 'COMMENT_UPLOADING_SUCCESS';
export const COMMENT_UPLOADING_FAILURE = 'COMMENT_UPLOADING_FAILURE';

export const COMMENT_LOADING_REQUEST = 'COMMENT_LOADING_REQUEST';
export const COMMENT_LOADING_SUCCESS = 'COMMENT_LOADING_SUCCESS';
export const COMMENT_LOADING_FAILURE = 'COMMENT_LOADING_FAILURE';

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';

export const CLEAR_COMMENT_ERROR_REQUEST = 'CLEAR_COMMENT_ERROR_REQUEST';
export const CLEAR_COMMENT_ERROR_SUCCESS = 'CLEAR_COMMENT_ERROR_SUCCESS';
export const CLEAR_COMMENT_ERROR_FAILURE = 'CLEAR_COMMENT_ERROR_FAILURE';

export const ON_SUCCESS_BUY_USER = 'ON_SUCCESS_BUY_USER';

export const UPLIKE_REQUEST = 'UPLIKE_REQUEST';
export const UPLIKE_SUCCESS = 'UPLIKE_SUCCESS';
export const UPLIKE_FAILURE = 'UPLIKE_FAILURE';

export const UNLIKE_REQUEST = 'UNLIKE_REQUEST';
export const UNLIKE_SUCCESS = 'UNLIKE_SUCCESS';
export const UNLIKE_FAILURE = 'UNLIKE_FAILURE';
