export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

export const AUTH_USER = 'AUTH_USER';

export const ADD_TO_CART_USER_REQUEST = 'ADD_TO_CART_USER_REQUEST';
export const ADD_TO_CART_USER_SUCCESS = 'ADD_TO_CART_USER_SUCCESS';
export const ADD_TO_CART_USER_FAILURE = 'ADD_TO_CART_USER_FAILURE';

export const GET_CART_ITEMS_USER_REQUEST = 'GET_CART_ITEMS_USER_REQUEST';
export const GET_CART_ITEMS_USER_SUCCESS = 'GET_CART_ITEMS_USER_SUCCESS';
export const GET_CART_ITEMS_USER_FAILURE = 'GET_CART_ITEMS_USER_FAILURE';

export const POST_DETAIL_LOADING_REQUEST = 'POST_DETAIL_LOADING_REQUEST';
export const POST_DETAIL_LOADING_SUCCESS = 'POST_DETAIL_LOADING_SUCCESS';
export const POST_DETAIL_LOADING_FAILURE = 'POST_DETAIL_LOADING_FAILURE';

export const PROFILE_EDIT_REQUEST = 'PROFILE_EDIT_REQUEST';
export const PROFILE_EDIT_SUCCESS = 'PROFILE_EDIT_SUCCESS';
export const PROFILE_EDIT_FAILURE = 'PROFILE_EDIT_FAILURE';

export const 